/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.unzip;
import com.looprecur.unzip.Decompress;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.os.Environment;
import java.io.File;

@Kroll.module(name="Unzip", id="com.looprecur.unzip")
public class UnzipModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "UnzipModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	public UnzipModule() {
		super();
	}
	

	// Methods
	@Kroll.method
	public void unzip(String zipFile, String unzipPath) {
		int plen = "file://".length();
		String sourcefile = zipFile.substring(plen);
		String dirout = unzipPath.substring(plen);
		Log.d(LCAT, "==============STARTING: " + sourcefile);
		Log.d(LCAT, "==============TO: " + dirout);
		
		Decompress d = new Decompress(sourcefile, dirout);
		d.unzip(); 
		Log.d(LCAT, "==============DONE=========");
	}

}
