/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.gestures;

import org.appcelerator.kroll.KrollModule;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

@Kroll.module(name="Gestures", id="com.looprecur.gestures")
public class GesturesModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "GesturesModule";
	private static final boolean DBG = TiConfig.LOGD;

	
	public GesturesModule() {
		super();
	}


}
