/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.package_manager;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollInvocation;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import org.appcelerator.titanium.TiApplication;

import android.content.pm.PackageManager;

import android.app.Activity;
import android.content.Intent;


@Kroll.module(name="PackageManager", id="com.looprecur.package_manager")
public class PackageManagerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "PackageManagerModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public PackageManagerModule() {
		super();
	}

	// Methods
	@Kroll.method
	public void launch(KrollInvocation invocation, String packageName) {
		final Activity activity = TiApplication.getAppRootOrCurrentActivity();
		PackageManager pm = (PackageManager) activity.getPackageManager();
    Intent launchIntent = pm.getLaunchIntentForPackage(packageName);
		activity.startActivity(launchIntent);
	}

}
