/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.aqlibandroid;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollDict;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.titanium.util.TiActivitySupport;
import android.content.Intent;
import android.app.Activity;

import java.util.HashMap;
import java.lang.Exception;

@Kroll.module(name="Aqlibscanner", id="com.looprecur.aqlibandroid")
public class AqlibscannerModule extends KrollModule implements TiActivityResultHandler
{
  private KrollFunction success;
  private KrollFunction error;

	public AqlibscannerModule()
	{
		super();
	}

	@Kroll.method
	public void scanVin(HashMap args)
	{
    success = (KrollFunction) args.get("success");
    error = (KrollFunction) args.get("error");

    Activity appActivity = getActivity();
    TiActivitySupport support = (TiActivitySupport) appActivity;
    Intent intent = new Intent(appActivity, ScanBarcodeActivity.class);
    support.launchActivityForResult(intent, 10, this);
	}
  
  @Override
  public void onResult(Activity activity, int requestCode, int resultCode, Intent data)
  {
    KrollDict evt = new KrollDict();
    String vin = data.getStringExtra("vin");
    evt.put("vin", vin);
    success.call(getKrollObject(), evt);
  }

  @Override
  public void onError(Activity activity, int requestCode, Exception e)
  {
    KrollDict evt = new KrollDict();
    String msg = e.toString();
    evt.put("msg", msg);
    error.call(getKrollObject(), evt);
  }

}
