/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.restart;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

@Kroll.module(name="Restart", id="com.looprecur.restart")
public class RestartModule extends KrollModule
{	
	private static final String LCAT = "RestartModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	static {
    System.loadLibrary("restartmodule");
  }

	public RestartModule(TiContext tiContext) {
		super(tiContext);
	}

	// Methods
	@Kroll.method
	public void restart() {
		Log.d(LCAT, "RESTARTING......");
		tomestoneCrash();
	}
	
	protected native void tomestoneCrash();
}
