/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.looprecur.apk_install;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.content.Intent;
import java.io.File;
import android.net.Uri;
import android.app.Activity;

@Kroll.module(name="Apkinstall", id="com.looprecur.apk_install")
public class ApkinstallModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ApkinstallModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ApkinstallModule() {
		super();
	}

	// Methods
	@Kroll.method
	public void promptInstall(String filepath){
		int plen = "file://".length();
		String fixed_path = filepath.substring(plen);
		File file = new File(fixed_path);
		final Activity activity = TiApplication.getAppRootOrCurrentActivity();
		Intent intent = new Intent(Intent.ACTION_VIEW);
	 	intent.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");
	 	activity.startActivity(intent);
	}

}
